!!python/object:argparse.Namespace
data: !!python/object:argparse.Namespace
  dataset: Sudoku
  dataset_length: 1000000
  finite_length: false
  fit_intermediate: true
  n_cont: 0
  num_workers: 4
  obs_props:
  - 0.0
  - 0.2
  - 0.5
  - 0.8
  save_sparsity_mask: false
  supervise_intermediate: true
  test_dataset_length: 100
  type: 6
  vary_dimensions: false
device: !!python/object/apply:torch.device
- cpu
diffusion: !!python/object:argparse.Namespace
  beta_end: 0.005
  beta_schedule: linear
  beta_start: 0.0001
  num_diffusion_timesteps: 1000
model: !!python/object:argparse.Namespace
  attn_dim_reduce: 1
  attn_reg_lambda: 0.0
  attn_reg_mu: 0.5
  conditional: fixed
  cross_entropy_loss: false
  ema: true
  ema_rate: 0.999
  emb_dim: 128
  impose_sparsity: sparse
  max_attn_matrix_size: 40000
  n_heads: 8
  num_transformers: 6
  predict: x0
  resnet: true
  softmax: true
  type: simple
  use_shared_var_embeds: true
  use_shared_var_positions: false
  var_embedding: true
  var_type: fixedlarge
optim: !!python/object:argparse.Namespace
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 2.0e-05
  optimizer: Adam
  weight_decay: 0.0
sampling: !!python/object:argparse.Namespace
  fixed_batch: false
  last_only: true
  sampling_batch_size: 16
training: !!python/object:argparse.Namespace
  attn_reg_iters: 1000
  batch_size: 32
  max_epoch_iters: 5000
  mean_latents_loss: false
  n_epochs: 1000
  snapshot_freq: 5000
  validation_freq: 2000
